spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/empresa
    username: postgres
    password: 9801Sauloyuri!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true